### ISSUE TITLE
optimization on steps

### ISSUE THREAD

**Issue by saaraahfar** [mcmonkeyprojects/sd-infinity-grid-generator-script#22]
when defining multiple steps from the range of 2 to 50, the generator goes through all of them from step 0, it would be nice if the optimization happen so in the middle of the steps it saves the pictures and continue where it left off

**Comment by mcmonkey4eva** [comment]
So, that's actually a fun topic! It doesn't actually work that way!
going from 20 to 40 steps doesn't just do twice as many steps... it does twice as many steps *with half as much change per step*.

For example, here's Euler generating a cat for 6 steps:
![](https://i.alexgoodwin.media/i/misc/e7b3d2.png)

and the same cat for 40 steps:
![](https://i.alexgoodwin.media/i/misc/ce63e8.png)

Compare sample-5 on the 6-step to sample-5 the 40-step.

Barely even similar!

The differences are even worse if you use `SDE` (stochastic) or any of the `a` (ancestral) variant samplers.

Each step of SD isn't just taking the image and trying to make it better, it's taking an image at for example 50% noise and trying to decide what the image should look like at 40% noise - this is the heart of 'diffusion' AI models. Rather than training an AI to generate images, they are trained to remove a small percent of noise per step, and do that repeatedly.
Adding more steps adds more quality because each step doesn't have to create as much new information, because the % of noise it needs to remove is lower.

The AI knows what step it's on... it's not just "remove 2% noise", it's "bring this image from 54% noisey to 52% noisey".

\* Note for the record that even now I'm still slightly simplifying and anthropomorphizing. 

----------

Side note, if you wanted to see what would happen if you took the idea you had and applied it anyway despite SD not quite working how you thought, you can try that! Create an img in txt2img, then send it to img2img, copy the seed/sampler/prompt/etc over, pick a denoising amount and run the img2img. You'll get a different result than if you just increased the step count.

----------

So, bad news: can't optimize things that way.
Good news: you learned something new about SD :D
