### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by yggdrasil75** [mcmonkeyprojects/sd-infinity-grid-generator-script#33]
based on my experiments, I can generate 4 images with most of my models (basically anything pruned) with a negligible increase in average time per image (from 4.6 it/s to 4.2 it/s was the difference on one I use often) I tried enabling batch of 4 to generate 4 and see a comparison of 4 different seeds with each selected model/sampler/prompt replacement but it still only generated 1. I do not know how batching works on the back end, but can it be made where either you specify multiple seeds and it generates all specified as a single batch job, or if the generation engine allows, that it generates a specified number of images as a single batch (would probably only work with promptreplace I would guess), so that it takes less time for the entire grid to generate (current grid is 45 hours to generate, I am at 10 in cause I keep wanting to do other things)

**Comment by appleguy** [comment]
+1 - @mcmonkey4eva this could actually greatly improve performance for many users. On a 4090, even with the various performance fixes in place, I see 14-15 it/s but achieve 43 it/s with a batch size of 4.

I'm wondering if this could be more easily addressed with a naive implementation, e.g., use batching only in the deepest "leaf" traversal where most parameters are identical. Even if that resulted in uneven performance, like some batches of 4, 2, or 1, it could still greatly improve the throughput of large jobs.

This is actually where this project excels beyond anything else currently available: exploring a very large space of options. As such, getting maximum throughput this way could be quite valuable and enable some workflows that are impractical without it.

**Comment by yggdrasil75** [comment]
https://github.com/yggdrasil75/sd-infinity-grid-generator-script @appleguy try this. delete the installed extension from the extensions folder and install this with the install from url option in extensions. restart a1111 completely afterwards (not just the "apply and restart" button) it appears to be working.

**Comment by appleguy** [comment]
Amazing, thanks!! I will gladly give this a try in the next 24-48hrs.

**Comment by appleguy** [comment]
@yggdrasil75 successfully installed (and full relaunch), though with a quick test I ran into this exception - should I leave the Batch Size unset in the UI? In this case, I tried setting it to 4.

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 439, in run
    result = core.runGridGen(p, grid_file, p.outpath_grids, output_file_path, do_overwrite, fast_skip, generate_page, publish_gen_metadata, dry_run, manualAxes)
  File "D:\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 654, in runGridGen
    result = runner.run(dryRun)
  File "D:\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 468, in run
    prompt_batch_list = self.batch_prompts(prompt_batch_list, self.p)
  File "D:\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 483, in batch_prompts
    non_sampler_name_attrs = set((attr, getattr(p, attr)) for attr in dir(p) if attr != 'prompt' and attr != 'batch_size' and attr != 'sampler_name')
TypeError: unhashable type: 'dict'

**Comment by appleguy** [comment]
Thanks again *very* much for working on this @yggdrasil75 - it's quite a cool technical challenge too.

I pulled your latest repo updates, and do see different output, although not yet success - happy to keep testing with you.

**Is it supposed to have a Batch Size set in the UI,** or does the script consider that automatically / internally? Just want to make sure I'm not messing it up by setting my own Batch Size of 4.

Here's the output I get, but right after this no processing occurs and it returns control -- so the UI also has a "Generate" button again instead of the Interrupt / Skip buttons.

`Have 36 unique value sets, will go into StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43
Skipped 0 files, will run 36 files, for 2880 total steps
Building final web data...
Web file is now at StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/index.html
                                  On 1/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/1/1t [00:00, ?it/s]
On 2/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/1/2
On 3/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/1/3
On 4/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/1/4
On 5/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/2/1
On 6/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/2/2
On 7/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/2/3
On 8/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/2/4
On 9/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/3/1
On 10/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/3/2
On 11/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/3/3
On 12/36 ... Set: CFG Scale=10.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/1/3/4
On 13/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/1/1
On 14/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/1/2
On 15/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/1/3
On 16/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/1/4
On 17/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/2/1
On 18/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/2/2
On 19/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/2/3
On 20/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/2/4
On 21/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/3/1
On 22/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/3/2
On 23/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/3/3
On 24/36 ... Set: CFG Scale=15.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/2/3/4
On 25/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/1/1
On 26/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/1/2
On 27/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/1/3
On 28/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=7.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/1/4
On 29/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/2/1
On 30/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/2/2
On 31/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/2/3
On 32/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=10.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/2/4
On 33/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=1, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/3/1
On 34/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=2, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/3/2
On 35/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=3, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/3/3
On 36/36 ... Set: CFG Scale=25.0, [DynamicThreshold] Mimic Scale=15.0, ClipSkip=4, file StableDiffusion/txt2img-grids\autonamed_inf_grid_31_03_2023_16_57_43/3/3/4
processing prompt 1/36 to add to groups
processing prompt 2/36 to add to groups
processing prompt 3/36 to add to groups
processing prompt 4/36 to add to groups
processing prompt 5/36 to add to groups
processing prompt 6/36 to add to groups
processing prompt 7/36 to add to groups
processing prompt 8/36 to add to groups
processing prompt 9/36 to add to groups
processing prompt 10/36 to add to groups
processing prompt 11/36 to add to groups
processing prompt 12/36 to add to groups
processing prompt 13/36 to add to groups
processing prompt 14/36 to add to groups
processing prompt 15/36 to add to groups
processing prompt 16/36 to add to groups
processing prompt 17/36 to add to groups
processing prompt 18/36 to add to groups
processing prompt 19/36 to add to groups
processing prompt 20/36 to add to groups
processing prompt 21/36 to add to groups
processing prompt 22/36 to add to groups
processing prompt 23/36 to add to groups
processing prompt 24/36 to add to groups
processing prompt 25/36 to add to groups
processing prompt 26/36 to add to groups
processing prompt 27/36 to add to groups
processing prompt 28/36 to add to groups
processing prompt 29/36 to add to groups
processing prompt 30/36 to add to groups
processing prompt 31/36 to add to groups
processing prompt 32/36 to add to groups
processing prompt 33/36 to add to groups
processing prompt 34/36 to add to groups
processing prompt 35/36 to add to groups
processing prompt 36/36 to add to groups
added all to groups
Total progress:   0%|                                                                                                                                 | 0/2880 [00:00<?, ?it/s]`

**Comment by yggdrasil75** [comment]
yeah, its still broken. I had it kinda working but then apparently when removing my excessive logging I deleted something that was necessary, causing a crash. one of the prior prs should be able to generate batch size at a time (you set it in the ui) but it was saving only the first because I thought that the save file path was in set but its in p instead. (great naming conventions all around. I know p comes from a1111, but still… changed it to promptkey)

I am getting slightly further each time understanding what is going on, but I dont know python so its a bunch of w3schools and chatgpt as I muddle through.

**Comment by yggdrasil75** [comment]
@appleguy I fixed it. https://github.com/yggdrasil75/sd-infinity-grid-generator-script/commit/af2ababaddd8e815339a94489fa6ee567dca9e96

or at least, it saved 4 different files with 1 generation. it will certainly require more testing for a few minor things (ie: when it reaches the end, if it doesnt have a full batch, I dont know what it does… and I havent gotten to it switching models yet in my testing)

also, I need to add it to the yaml options list, though that might be a little easier now.

**Comment by appleguy** [comment]
This is awesome - however, shouldn't this issue remain open until e.g. a PR is merged to this repo? @yggdrasil75 

I had been following your changes for a few days, pulling the latest and trying again, but ironically just a few hours before your last fixes I reverted back to the main repo because I wanted to run a large grid generation :). I haven't yet had a chance to switch repos again, but will try to do so by this weekend.
