### ISSUE TITLE
Dynamic Prompts tandem

### ISSUE THREAD

**Issue by Artemonim** [mcmonkeyprojects/sd-infinity-grid-generator-script#35]
## Problem

I am a Dynamic Prompts user. In this extension the separator is the symbol `|`, which is good because this symbol is not usually present in the usual prompt.

DP allows you to generate several variants of the images at once, but it does not work in tandem with Plot XYZ.

However, DP works with the Infinity Grid... just doesn't save all the results :/
![2023-03-12_03-45-45](https://user-images.githubusercontent.com/36363466/224518155-705695ec-c0bc-40cd-b73d-ef02c3c92143.png)
```
prompt: woman {wears a red cloak|in ikebana dress|wears a black hooded cloak made of zinnias}, {standing outside on the beach at sunset|in an old soviet city, hyper real, fantasy world|holding an umbrella in her hands, eonn}
CFG Scale: 4, 8
```

## Request
So I either need:
- Infinite Grid to be able to save all images generated in tandem with Dynamic Prompts,
- either `Prompt Replace` to use `|` as a separator instead of `,` so that I can drop DP in favor of IG.

**Comment by mcmonkey4eva** [comment]
Good news! I already thought of this :D

All comma-separated inputs allow you to use `||` (ie two pipes instead of one, which is to deconflict with other things that use pipes sometimes). If you have `||` present, that will be used and `,` will be ignored (and kept as part of the prompt text itself).

If you want to create a superset of that example prompt via inf grid generator, you could for example set prompt to `prompt: woman {a}, {b}`
then axis 1 = Prompt replace with value `{a}= wears a red cloak || {a}= in ikebana dress || {a}= wears a black hooded cloak made of zinnias`
and axis 2 = prompt replace with value `{b}= standing outside on the beach at sunset || {b}= in an old soviet city, hyper real, fantasy world|| {b}= holding an umbrella in her hands, eonn`

**Comment by Artemonim** [comment]
@mcmonkey4eva add this to the readme please 👉👈😳

**Comment by SMUsamaShah** [comment]
To avoid splitting by commas in a single long prompt i used double pipes at the end e.g. `my, very, long, single, prompt, with, commas ||` but this creates a second empty prompt for all the combinations. How do I avoid that? 

I think best would be to ignore empty prompt when double pipes are used

**Comment by mcmonkey4eva** [comment]
Er... if your list only has one value in it, why are you putting it in an axis at all? 0.o

**Comment by SMUsamaShah** [comment]
I put it on axis because i don't run all prompts in one go. I'll do one prompt at a time. Then if i found another interesting prompt, i'll do another run with just that prompt. This will add all my new runs with new prompts etc on the same page.
