### ISSUE TITLE
Request: Export as XY plot

### ISSUE THREAD

**Issue by Artemonim** [mcmonkeyprojects/sd-infinity-grid-generator-script#39]
### Problem
![2023-03-13_16-41-52](https://user-images.githubusercontent.com/36363466/224719626-410b7f18-c889-479a-a2f0-1c44a5dc50a7.png)
![2023-03-13_16-40-27](https://user-images.githubusercontent.com/36363466/224719644-98858ab1-fa57-40e8-bda6-8ec09bbbefa8.png)

## Requests
- Add export as png for all two-dimensional grid variations
- Add export as png for current 2D grid selection
- Add export as png for current 3D grid selection (as in XYZ Plot script)

### Or make the process of exploring large grids as convenient and smooth as in Windows Image Viewer
[Make the process of exploring large grids as convenient and smooth as in Windows Image Viewer](https://user-images.githubusercontent.com/36363466/224748349-477a078a-b276-496d-be3b-71e07e7adb4a.mp4)

Yes, these are different things, but I need this smooth view, I'm fine with Windows Viewer, so I thought it would be easier to integrate the export feature rather than make dynamic zooming 😅7

However, the export as PNG is also something I want to have 🙂

**Comment by mcmonkey4eva** [comment]
There's now a lil button at the top above the main image table:
![image](https://user-images.githubusercontent.com/4000772/233776225-e9e65ad6-52e6-47de-a178-abe9af57ed33.png)
and you can click it:
![image](https://user-images.githubusercontent.com/4000772/233776235-c8faa4f2-074a-4f60-bbcb-6752f7389450.png)
to get an image file of whatever your current view on-page is.
Inherently supports any view configuration (super-axes, hidden items, etc) because it's processed on the webviewer itself in javascript.
The resultant image you can simply `right click -> save as` or `copy image`

You can also `open in new tab` but, uh, might lag, depending on browser, as generated images behave weird (blob urls).
