### ISSUE TITLE
TypeError: 'float' object is not callable

### ISSUE THREAD

**Issue by guubi-sd** [mcmonkeyprojects/sd-infinity-grid-generator-script#8]
Hello

Trying to get this working as it seems amazing, but every time I get an error after generation.
Dry runs work fine, the generated page works fine, the generation works fine (I can see the generated images in the relative folders) but right at the end it errors with "TypeError: 'float' object is not callable"

Console output:
> Error completing request
Arguments: ('cat, feline, feral, big eyes, sharp eyes, abstract, 4k, bokeh, full body, abstract background, flowers, pattern, gradient, design, cover page, front cover, movie poster', 'lowres, bad anatomy, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry', 'None', 'None', 23, 0, False, False, 1, 1, 11, 1149236390.0, -1.0, 0, 0, 0, False, 640, 512, False, 0.7, 0, 0, 4, False, False, False, False, '', 1, '', 0, '', True, False, False, '<br>Confused/new? View <a style="border-bottom: 1px #00ffff dotted;" href="https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script">the README</a> for usage instructions.<br><br>', True, True, False, True, True, 'cattest.yml', '🔄') {}
Traceback (most recent call last):
  File "H:\AI TEST\FRESH\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\AI TEST\FRESH\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "H:\AI TEST\FRESH\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "H:\AI TEST\FRESH\stable-diffusion-webui\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "H:\AI TEST\FRESH\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 612, in run
    with SettingsFixer():
  File "H:\AI TEST\FRESH\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 433, in __exit__
    hypernetwork.apply_strength()
TypeError: 'float' object is not callable

I've tried updating, re-installing the extension, even running it on a fresh SD install. I've tried the example scripts provided and no luck.

[cattest.yml](https://pastebin.com/qfXhXTMd) [pastebin]

**Comment by mcmonkey4eva** [comment]
Oops, HypernetworkStrength wasn't tested.

The new commit above fixes the code for hn strength.

But also, your test yaml file had a couple minor issues:
A: You were missing `values:` under `hypernetwork` .. might be you deleted some hn entries before posting and accidentally deleted too many lines?
B: Your Hypernetwork Strength file had values with keys like `0.75:` - YAML doesn't allow `.` in key names, so that can be changed something like `0_75` to make it work (the `.` is fine everywhere other than the key)
So like:
```yml
            0_75: 
                title: 0.75
                params:
                    HypernetworkStrength: 0.75
```
Alternately you can just give lazy key names like `1:`, `2:`, `3:` since those keys only decide the file path and not much else.

With the code update and those lil yaml patches applied, it's working as intended now!

**Comment by guubi-sd** [comment]
Thanks for this - working perfectly fine now :)

Not sure why the paste somehow deleted 4 lines? `values:` was in the original file.
I've changed the formatting in the key names also.

Sweet extension 👍 will help me a lot.
